name: Telegram Trades to TradeLocker

on:
  schedule:
    - cron: '3,33 * * * *'
  workflow_dispatch:

jobs:
  trade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Execute TradeLocker Bot
        env:
          TL_EMAIL: ${{ secrets.TL_EMAIL }}
          TL_PASSWORD: ${{ secrets.TL_PASSWORD }}
          TL_SERVER: ${{ secrets.TL_SERVER }}
          TL_ACCOUNT_ID: ${{ secrets.TL_ACCOUNT_ID }}
          TL_ACC_NUM: ${{ secrets.TL_ACC_NUM }}
          TL_ENV: ${{ secrets.TL_ENV }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT: ${{ secrets.TG_CHAT }}
          TL_PAIR_MAP: ${{ secrets.TL_PAIR_MAP }}
          TL_DEFAULT_QTY: ${{ secrets.TL_DEFAULT_QTY }}
        run: python3 tradelocker_telegram_bot.py
